### ISSUE TITLE
Wrong projection string for data

### ISSUE THREAD

**Issue by barryrowlingson** [dshean/hma_mb_paper#1]
The readme file here: 

https://github.com/dshean/hma_mb_paper/tree/ec888449d074f8f4af6e88030ded14006869b0d7/data/mb

says the coordinates in the CSV files have a PROJ4 string: "PROJ4 string '+proj=aea +lat_1=36 +lat_2=49 +lat_0=43 +lon_0=-115 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

but this puts them on the west coast of the USA and into the Pacific.

The correct poj4 string appears to be:

"+proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"

which is the one specified here: https://github.com/dshean/hma_mb_paper/blob/ec888449d074f8f4af6e88030ded14006869b0d7/scripts/rgi_dem_trend_prep.sh#L85

This seems to put the data in the right place.

**Comment by dshean** [comment]
Thank you for reporting this @barryrowlingson!  I copied the wrong line when preparing the doc.  Fixed!
